name: master-release

permissions:
  contents: write

on:
  push:
    branches:
      - "master"

jobs:
  master-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Build windows x86
        run: GOOS=windows GOARCH=386 go build -o octopus-wechat-x86.exe main.go

      - name: Build windows x64
        run: GOOS=windows GOARCH=amd64 go build -o octopus-wechat-x64.exe main.go

      - name: Generate release tag
        id: tag
        env:
          TZ: Asia/Shanghai
        run: |
          echo "::set-output name=release_tag::master_$(date +"%Y%m%d%H%M")"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            octopus-wechat-x86.exe
            octopus-wechat-x64.exe
